import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { cn } from "@/lib/utils";
import { geistMono } from "@/styles/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(geistMono.variable)}>
      <body
        className={` h-full min-h-screen`}
      >
        <Providers>
          <div className="relative h-full">
            <main className="relative  flex-1">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
